"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, BarChart3, CheckCircle2, Gauge, LockKeyhole, Mail, Share2, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

const features = [
  {
    icon: Gauge,
    title: "Deterministic savings engine",
    copy: "Plan, seat, and usage rules calculate savings without handing math to a model."
  },
  {
    icon: Sparkles,
    title: "Personalized summary",
    copy: "OpenAI turns the hard numbers into a concise operator-ready readout."
  },
  {
    icon: Share2,
    title: "Public report links",
    copy: "Share a sanitized report with founders, finance, or engineering leaders."
  },
  {
    icon: LockKeyhole,
    title: "No login required",
    copy: "Run the audit in minutes, capture the result, and move on with your day."
  }
];

const steps = ["Add your AI stack", "Review plan and seat fit", "Get savings and recommendations", "Share or email the report"];

const faqs = [
  {
    q: "Is the audit generated by AI?",
    a: "The calculations are deterministic and based on pricing rules. AI is only used to summarize the result in plain language."
  },
  {
    q: "Do I need to connect billing data?",
    a: "No. The first version uses self-reported monthly spend, seats, and plan selection so teams can get a quick directional audit."
  },
  {
    q: "What happens to private details on public reports?",
    a: "Public URLs remove lead details and expose only the sanitized audit result, recommendations, totals, and tool count."
  },
  {
    q: "Who is Credex?",
    a: "Credex is positioned as the consultation partner for teams with high potential savings who want implementation help."
  }
];

export function LandingPage() {
  return (
    <div className="overflow-hidden">
      <section className="relative border-b">
        <div className="absolute inset-0 -z-10 bg-[linear-gradient(135deg,hsl(var(--background)),hsl(var(--secondary)),hsl(var(--background)))]" />
        <div className="container grid min-h-[calc(100vh-4rem)] items-center gap-10 py-16 lg:grid-cols-[1fr_0.9fr]">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="max-w-3xl"
          >
            <Badge variant="secondary" className="mb-6">
              Free AI tooling audit for startup teams
            </Badge>
            <h1 className="text-balance text-5xl font-semibold tracking-normal text-foreground sm:text-6xl lg:text-7xl">
              AI Spend Audit
            </h1>
            <p className="mt-6 max-w-2xl text-balance text-lg leading-8 text-muted-foreground sm:text-xl">
              Find plan waste, unused seats, and API spend leakage across Cursor, Copilot, ChatGPT, Claude, OpenAI,
              Anthropic, Gemini, and Windsurf.
            </p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row">
              <Button asChild size="lg">
                <Link href="/audit">
                  Start free audit <ArrowRight className="h-4 w-4" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg">
                <Link href="#how-it-works">See how it works</Link>
              </Button>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 32 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.15 }}
            className="rounded-2xl border bg-card p-4 shadow-glow"
            aria-label="Example AI spend audit result"
          >
            <div className="rounded-xl border bg-background p-5">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Estimated monthly savings</p>
                  <p className="mt-1 text-4xl font-semibold">$1,240</p>
                </div>
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/12 text-primary">
                  <BarChart3 className="h-6 w-6" />
                </div>
              </div>
              <div className="mt-6 grid gap-3">
                {[
                  ["OpenAI API", "$720", "Add caps and routing"],
                  ["Cursor", "$280", "Remove unused seats"],
                  ["ChatGPT", "$240", "Downgrade 8 seats"]
                ].map(([tool, amount, action]) => (
                  <div key={tool} className="flex items-center justify-between rounded-lg border bg-card p-4">
                    <div>
                      <p className="font-medium">{tool}</p>
                      <p className="text-sm text-muted-foreground">{action}</p>
                    </div>
                    <p className="font-semibold text-primary">{amount}</p>
                  </div>
                ))}
              </div>
              <div className="mt-6 rounded-lg bg-secondary p-4 text-sm text-muted-foreground">
                Your stack has meaningful savings without changing core workflows. Start with seat cleanup, then
                enforce API budget controls.
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      <section id="features" className="container py-20">
        <div className="max-w-2xl">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">What you get</p>
          <h2 className="mt-3 text-3xl font-semibold sm:text-4xl">A polished finance readout, not a toy calculator.</h2>
        </div>
        <div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          {features.map((feature) => (
            <Card key={feature.title}>
              <CardContent className="p-6">
                <feature.icon className="h-6 w-6 text-primary" />
                <h3 className="mt-5 font-semibold">{feature.title}</h3>
                <p className="mt-2 text-sm leading-6 text-muted-foreground">{feature.copy}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      <section id="how-it-works" className="border-y bg-secondary/35 py-20">
        <div className="container">
          <div className="grid gap-10 lg:grid-cols-[0.8fr_1fr] lg:items-start">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">How it works</p>
              <h2 className="mt-3 text-3xl font-semibold sm:text-4xl">From messy spend to a shareable report.</h2>
            </div>
            <div className="grid gap-3">
              {steps.map((step, index) => (
                <div key={step} className="flex items-center gap-4 rounded-xl border bg-card p-5">
                  <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-primary text-sm font-semibold text-primary-foreground">
                    {index + 1}
                  </span>
                  <p className="font-medium">{step}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="container py-20">
        <div className="grid gap-4 lg:grid-cols-3">
          {[
            ["Founder-friendly", "“The report gave us a clean way to discuss AI spend without turning it into tool politics.”"],
            ["Finance-ready", "“We found redundant seats in under ten minutes and had a board-safe summary the same day.”"],
            ["Engineering-aware", "“It did not just say cut everything. It separated useful tools from obvious plan waste.”"]
          ].map(([title, quote]) => (
            <Card key={title}>
              <CardContent className="p-6">
                <CheckCircle2 className="h-5 w-5 text-primary" />
                <h3 className="mt-4 font-semibold">{title}</h3>
                <p className="mt-3 text-sm leading-6 text-muted-foreground">{quote}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      <section id="faq" className="border-t bg-secondary/30 py-20">
        <div className="container grid gap-10 lg:grid-cols-[0.7fr_1fr]">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">FAQ</p>
            <h2 className="mt-3 text-3xl font-semibold">Practical answers before you audit.</h2>
          </div>
          <div className="grid gap-3">
            {faqs.map((faq) => (
              <details key={faq.q} className="rounded-xl border bg-card p-5">
                <summary className="cursor-pointer font-semibold">{faq.q}</summary>
                <p className="mt-3 text-sm leading-6 text-muted-foreground">{faq.a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      <section className="container py-16">
        <div className="flex flex-col items-start justify-between gap-6 rounded-2xl border bg-card p-8 md:flex-row md:items-center">
          <div>
            <Mail className="mb-4 h-6 w-6 text-primary" />
            <h2 className="text-2xl font-semibold">Ready to see where AI spend is leaking?</h2>
            <p className="mt-2 text-muted-foreground">No auth. No integrations. Just a clear first-pass audit.</p>
          </div>
          <Button asChild size="lg">
            <Link href="/audit">
              Run the audit <ArrowRight className="h-4 w-4" />
            </Link>
          </Button>
        </div>
      </section>
    </div>
  );
}
